---
metricbeat_repo_manage: true
metricbeat_package_names: metricbeat
metricbeat_package_state: present
metricbeat_package_hold: false

metricbeat_service_name: metricbeat
metricbeat_service_status: started
metricbeat_service_enabled: true

metricbeat_conf_manage: yes
metricbeat_conf_path: /etc/metricbeat/metricbeat.yml
metricbeat_conf_modules_path: /etc/metricbeat/modules.d

metricbeat_conf_modules:
  - module: system
    metricsets:
      - cpu
      - load
      - core
      - diskio
      - filesystem
      - fsstat
      - memory
      - network
      - process
    enabled: true
    cpu.metrics:
      - percentages
      - normalized_percentages

metrccbeat_conf_output:
  enabled: true
  hosts: "localhost:9200"
  loadbalance: false

metricbeat_conf_setup:
  dashboards:
    enabled: false
  template:
    enabled: false
  ilm:
    enabled: false

metricbeat_conf_logging:
  level: warning
  to_syslog: false
  to_files: true
  files:
    path: /var/log/metricbeat
    name: metricbeat
    keepfiles: 7
    permissions: "0644"

metricbeat_conf_seccomp:
  enabled: false

metricbeat_conf_fields: {}

metricbeat_conf:
  metricbeat:
    config:
      modules:
        path: "{{ metricbeat_conf_modules_path }}/*.yml"
  output: "{{ metricbeat_conf_output }}"
  setup: "{{ metricbeat_conf_setup }}"
  logging: "{{ metricbeat_conf_logging }}"
  seccomp: "{{ metricbeat_conf_seccomp }}"
  fields: "{{ metricbeat_conf_fields }}"
