---
metricbeat_repo_manage: yes
metricbeat_package_names: metricbeat
metricbeat_package_state: present
metricbeat_package_hold: no

metricbeat_service_name: metricbeat
metricbeat_service_status: started
metricbeat_service_enabled: yes

metricbeat_conf_manage: yes
metricbeat_conf_path: /etc/metricbeat/metricbeat.yml
metricbeat_conf_modules_path: /etc/metricbeat/modules.d

metricbeat_conf_system_metricsets:
  - cpu
  - load
  - core
  - diskio
  - filesystem
  - fsstat
  - memory
  - network
  - process

metricbeat_conf_docker_metricsets:
  - container
  - cpu
  - diskio
  - healthcheck
  - info
  - image
  - memory
  - network
metricbeat_conf_docker_hosts:
  - unix:///var/run/docker.sock
metricbeat_conf_docker_packages:
  - docker
  - docker-ce
  - docker.io
  - docker-engine
metricbeat_conf_docker_period: 5s
metricbeat_conf_docker_installed: "{{ metricbeat_conf_docker_packages | intersect(ansible_facts.packages.keys() | list) | length > 0 }}"

metricbeat_conf_postgresql_metricsets:
  - database
  - bgwriter
  - activity
metricbeat_conf_postgresql_hosts:
  - postgres://localhost:5432
metricbeat_conf_postgresql_packages:
  - postgresql-server
metricbeat_conf_postgresql_period: 10s
metricbeat_conf_postgresql_installed: "{{ metricbeat_conf_postgresql_packages | intersect(ansible_facts.packages.keys() | list) | length > 0 }}"

metricbeat_conf_nginx_metricsets:
  - stubstatus
metricbeat_conf_nginx_period: 10s
metricbeat_conf_nginx_hosts:
  - http://localhost
metricbeat_conf_nginx_packages:
  - nginx
metricbeat_conf_nginx_status_path: nginx_status
metricbeat_conf_nginx_installed: "{{ metricbeat_conf_nginx_packages | intersect(ansible_facts.packages.keys() | list) | length > 0 }}"

metricbeat_conf_cpu_metrics:
  - percentages
  - normalized_percentages

metricbeat_conf_modules_base:
  - module: system
    metricsets: "{{ metricbeat_conf_system_metricsets }}"
    enabled: "{{ metricbeat_conf_system_enabled | default('yes') | bool }}"
    cpu.metrics: "{{ metricbeat_conf_cpu_metrics }}"
  - module: docker
    metricsets: "{{ metricbeat_conf_docker_metricsets }}"
    hosts: "{{ metricbeat_conf_docker_hosts }}"
    period: "{{ metricbeat_conf_docker_period }}"
    enabled: "{{ metricbeat_conf_docker_enabled | default(metricbeat_conf_docker_installed) }}"
  - module: nginx
    metricsets: "{{ metricbeat_conf_nginx_metricsets }}"
    hosts: "{{ metricbeat_conf_nginx_hosts }}"
    period: "{{ metricbeat_conf_nginx_period }}"
    enabled: "{{ metricbeat_conf_nginx_enabled | default(metricbeat_conf_nginx_installed) }}"
    server_status_path: "{{ metricbeat_conf_nginx_status_path }}"

metricbeat_conf_module_postgresql_base:
  module: postgresql
  metricsets: "{{ metricbeat_conf_postgresql_metricsets }}"
  hosts: "{{ metricbeat_conf_postgresql_hosts }}"
  period: "{{ metricbeat_conf_postgresql_period }}"
  enabled: "{{ metricbeat_conf_postgresql_enabled | default(metricbeat_conf_postgresql_installed) }}"
metricbeat_conf_module_postgresql_user:
  user: "{{ metricbeat_conf_postgresql_user | default(omit) }}"
  pass: "{{ metricbeat_conf_postgresql_pass | default(omit) }}"
metricbeat_conf_module_postgresql:
  - "{{ metricbeat_conf_module_postgresql_base | combine(metricbeat_conf_module_postgresql_user if (metricbeat_conf_postgresql_user is defined) and (metricbeat_conf_postgresql_pass is defined) else {}) }}"

metricbeat_conf_modules_extra: []
metricbeat_conf_modules: "{{ metricbeat_conf_modules_base + metricbeat_conf_module_postgresql + metricbeat_conf_modules_extra }}"

metricbeat_conf_elasticsearch_enabled: true
metricbeat_conf_elasticsearch_port: 9200
metricbeat_conf_elasticsearch_hosts: ['localhost']
metricbeat_conf_elasticsearch_loadbalance: true

metricbeat_conf_logstash_enabled: false
metricbeat_conf_logstash_port: 5044
metricbeat_conf_logstash_hosts: ['localhost']
metricbeat_conf_logstash_loadbalance: true

metricbeat_conf_dashboards_enabled: false
metricbeat_conf_dashboards_kibana: false
metricbeat_conf_template_enabled: true
metricbeat_conf_kibana_host: 'localhost:80'

metricbeat_conf_extra: {}

_metricbeat_conf_port_elasticsearch: "{{ metricbeat_conf_elasticsearch_port }}:"
_metricbeat_conf_port_logstash: "{{ metricbeat_conf_logstash_port }}:"

metricbeat_conf_output_elasticsearch:
  enabled: "{{ metricbeat_conf_elasticsearch_enabled }}"
  hosts: "{{ metricbeat_conf_elasticsearch_hosts | product([_metricbeat_conf_port_elasticsearch]) | map('join') | list }}"
  loadbalance: "{{ metricbeat_conf_elasticsearch_loadbalance }}"

metricbeat_conf_output_logstash:
  enabled: "{{ metricbeat_conf_logstash_enabled }}"
  hosts: "{{ metricbeat_conf_elasticsearch_hosts | product([_metricbeat_conf_port_logstash]) | map('join') | list }}"
  loadbalance: "{{ metricbeat_conf_logstash_loadbalance }}"

metricbeat_conf_output:
  elasticsearch: "{{ metricbeat_conf_output_elasticsearch }}"
  logstash: "{{ metricbeat_conf_output_logstash }}"

metricbeat_conf_setup:
  dashboards:
    enabled: "{{ metricbeat_conf_dashboards_enabled }}"
    beat: metricbeat
    always_kibana: "{{ metricbeat_conf_dashboards_kibana }}"
  template:
    enabled: "{{ metricbeat_conf_template_enabled }}"
  kibana:
    host: "{{ metricbeat_conf_kibana_host }}"

metricbeat_conf_logging:
  level: warning
  to_syslog: false
  to_files: true
  files:
    path: /var/log/metricbeat
    name: metricbeat
    keepfiles: 7
    permissions: 0644 # yamllint disable-line rule:octal-values

metricbeat_conf_base:
  metricbeat:
    config:
      modules:
        path: "{{ metricbeat_conf_modules_path }}/*.yml"
  output: "{{ metricbeat_conf_output }}"
  setup: "{{ metricbeat_conf_setup }}"
  logging: "{{ metricbeat_conf_logging }}"

metricbeat_conf: "{{ metricbeat_conf_base | combine(metricbeat_conf_extra) }}"
